/**Decision types */
export const DECISION_TYPES = {
  STANDARD_CONDITION: 'CONDITION - STANDARD',
  STANDARD_CONDITION_TREE: 'CONDITION FOR TREES - STANDARD',
  CLAUSE: 'INFORMATIVE CLAUSE - STANDARD',
  REASON_FOR_REFUSAL: 'REASON FOR REFUSAL - STANDARD',
  REASON_FOR_REFUSAL_TREE: 'REASON FOR REFUSAL FOR TREES - STANDARD',
  CUSTOM_CONDITION: 'CONDITION - CUSTOM`',
  CUSTOM_CONDITION_TREE: 'CONDITION FOR TREES - CUSTOM',
  CUSTOM_CLAUSE: 'INFORMATIVE CLAUSE - CUSTOM',
  CUSTOM_REASON_FOR_REFUSAL: 'REASON FOR REFUSAL - CUSTOM',
  CUSTOM_REASON_FOR_REFUSAL_TREE: 'REASON FOR REFUSAL FOR TREES - CUSTOM'
};
