import { UserInfo } from './../../common/userinfo';
import { DateRecord } from './../../common/date-record';
import { IRegistryDetails } from './../iregistry-details';

/**
 * Specifies the enforcement notice done
 */
export class Notice {

  public dates: DateRecord;

  /**Id of the linked document */
  public documentId: string;

  constructor(public type: string, public content: string, user: UserInfo) {
    this.dates = new DateRecord(user);
  }

  /**
   * Signs a notice with the specified user
   * @param user User signing the notice
   */
  sign(user: UserInfo) { this.dates.sign(user); }

  /**
   * Dispatches a notice by the specifed user
   * @param user User dispatching the notice
   */
  dispatch(user: UserInfo) { this.dates.dispatch(user); }

}

/**
 * Encapsulates the features for enforcement matters
 */
export class EnforcementFile implements IRegistryDetails {

  /**Notices generated by system */
  notices: Notice[];
}
